import type { Endpoint, PlatformUnderstanding } from "@scout/types";
import {
  envVarName,
  generateCode,
  selectReadEndpoint,
  type GenerateCodeOptions,
  type GenerateCodePlatform,
  type GeneratedCode,
} from "./generate-code.js";

export interface HandoffResult {
  markdown: string;
  workflowUsed: string | null;
  generatedCode: GeneratedCode;
}

/**
 * Neutralizes runs of 3+ backticks in spec/LLM-derived free text so it can't
 * close the markdown fenced code block early and inject content past it
 * (the doc this builds is meant to be pasted directly into a coding agent
 * as a task prompt, so a broken-out fence isn't just a rendering glitch,
 * it's an injection vector into whatever reads the doc next).
 */
function sanitizeForMarkdown(value: string): string {
  return value.replace(/`{3,}/g, (run) => run.split("").join("​"));
}

function bulletList(items: string[]): string {
  return items.map((item) => `- ${sanitizeForMarkdown(item)}`).join("\n");
}

/**
 * Bundles an already-synthesized understanding + generated starter code into
 * one paste-ready Markdown brief for a coding agent (Claude Code, Cursor,
 * etc.): the task, the auth handshake, a validated starter script, the env
 * vars it needs, the exact endpoint it calls, and the pitfalls/gaps Scout's
 * synthesis flagged, so the agent isn't starting from a blank page or
 * re-deriving what Scout already verified. Reuses generateCode's exact
 * output (same stub/validation honesty guarantees) rather than duplicating
 * codegen logic, and picks the same endpoint generateCode chose so the doc
 * and the script never describe two different calls.
 */
export async function assembleHandoff(
  understanding: PlatformUnderstanding,
  endpoints: Endpoint[],
  platform: GenerateCodePlatform,
  options: GenerateCodeOptions,
): Promise<HandoffResult> {
  const generatedCode = await generateCode(understanding, endpoints, platform, options);

  const name = sanitizeForMarkdown(platform.name);
  const workflow = generatedCode.workflowUsed
    ? understanding.commonWorkflows.find((w) => w.name === generatedCode.workflowUsed)
    : undefined;

  const sections: string[] = [];

  sections.push(`# Integration handoff: ${name}`);
  sections.push(
    "> Generated by Scout. Paste this into your coding agent (Claude Code, Cursor, etc.) as the task brief. Nothing here has been executed against the live API, so verify auth header/param names and the response shape before shipping.",
  );

  sections.push("## Task");
  if (workflow) {
    sections.push(`Implement the "${sanitizeForMarkdown(workflow.name)}" workflow:\n\n${bulletList(workflow.steps)}`);
  } else {
    sections.push(
      `No named workflow was targeted. Wire up a basic authenticated read against ${name}'s API, using the starter script below as the foundation.`,
    );
  }

  sections.push("## Authentication");
  const authLines = [sanitizeForMarkdown(understanding.authenticationFlow)];
  if (platform.authScheme) {
    authLines.push(`Scheme: \`${platform.authScheme}\``);
  }
  if (!generatedCode.isStub) {
    authLines.push(
      `Set \`${envVarName(platform.slug)}\` in your environment before running the script below (see \`.env.example\`).`,
    );
  }
  sections.push(authLines.join("\n\n"));

  if (platform.baseUrl) {
    sections.push(`## Base URL\n\n\`${sanitizeForMarkdown(platform.baseUrl)}\``);
  }

  sections.push(`## Starter code (${options.lang === "ts" ? "TypeScript" : "Python"})`);
  if (generatedCode.isStub) {
    sections.push(
      `Scout could not generate a real script for this run (${generatedCode.stubReason}). Showing an honest placeholder instead of fabricated code:`,
    );
  } else {
    if (generatedCode.workflowMismatch) {
      sections.push(
        "**Heads up:** the task above needs a write call, which Scout doesn't generate real code for yet (v1 only supports GET). The script below demonstrates the auth handshake and a basic read call instead -- it does NOT implement the task described above. Adapt it for the actual request.",
      );
    }
    sections.push(
      generatedCode.syntaxValidated
        ? `Syntax validated (${options.lang === "ts" ? "node --check" : "python3 -m py_compile"}) -- not tested against the live API.`
        : `Syntax not validated (${generatedCode.syntaxValidationNote ?? "unknown reason"}).`,
    );
  }
  sections.push(`\`\`\`${options.lang === "ts" ? "ts" : "py"}\n${generatedCode.code}\n\`\`\``);

  if (generatedCode.envExample) {
    sections.push(`## .env.example\n\n\`\`\`\n${generatedCode.envExample}\`\`\``);
  }

  const endpoint = endpoints.length > 0 ? selectReadEndpoint(endpoints, workflow) : undefined;
  if (endpoint) {
    const summary = endpoint.summary ? ` -- ${sanitizeForMarkdown(endpoint.summary)}` : "";
    sections.push(`## Endpoint used\n\n\`${endpoint.method} ${sanitizeForMarkdown(endpoint.path)}\`${summary}`);
  }

  if (understanding.potentialPitfalls.length > 0) {
    sections.push(`## Known pitfalls\n\n${bulletList(understanding.potentialPitfalls)}`);
  }

  if (understanding.securityObservations.length > 0) {
    sections.push(`## Security observations\n\n${bulletList(understanding.securityObservations)}`);
  }

  if (understanding.missingDocumentation.length > 0) {
    sections.push(
      `## Gaps Scout couldn't verify\n\n${bulletList(understanding.missingDocumentation)}\n\nDouble-check these against the platform's real docs before assuming them.`,
    );
  }

  return { markdown: `${sections.join("\n\n")}\n`, workflowUsed: generatedCode.workflowUsed, generatedCode };
}
